- title: "PhD representative for the EDI Committee"
  venue: "Institute of Cosmology &amp; Gravitation"
  dates: "2024 - 2026"
- title: "Local Organising Committee for the Simulation Based Inference for Galaxy Evolution Meeting"
  venue: "Bristol"
  dates: "2025"
- title: "Local Organising Committee for the VIRGO Consortium Meeting"
  venue: "University of Sussex"
  dates: "2025"
